import itertools

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million
, find the sum of the even-valued terms.
'''


class EvenFibonacci:
    def __init__(self):
        self.left = 1
        self.right = 1

    def get_n(self):
        while True:
            v = self.left + self.right
            (self.left, self.right) = (self.right, v)
            if v > 4000000:
                return
            if v % 2 == 0:
                yield v


fib = EvenFibonacci()
print sum(fib.get_n())