#! encoding: utf8
from profile_decorate import profile
from itertools import count
from math import sqrt

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal
"""


def is_triangle(n=None):
    return ((sqrt(8 * n + 1) + 1) / 2).is_integer()


def is_pentagonal(n=None):
    return ((sqrt(24 * n + 1) + 1) / 6).is_integer()


def get_hexagonal(n=None):
    return (2 * n - 1) * n


@profile
def main():
    NUMBERS_TO_FOUND = 3
    numbers_found = 0
    for i in count(1):
        candidate = get_hexagonal(i)
        if is_triangle(candidate) and is_pentagonal(candidate):
            print('candidate found {}'.format(candidate))
            numbers_found += 1
            if numbers_found == NUMBERS_TO_FOUND:
                break


if __name__ == '__main__':
    main()
