import math as math

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""


class TriangleList:
    def __init__(self):
        self.i = 1
        self.triangle_value = 0

    def get_triangle_value(self):
        while True:
            self.triangle_value += self.i
            self.i += 1
            yield self.triangle_value


triangle_inst = TriangleList()
for triangle_v in triangle_inst.get_triangle_value():
    divisor_num = 2
    sqrt_v = math.sqrt(triangle_v)
    for divisor in range(2, int(sqrt_v)):
        if triangle_v % divisor == 0:
            divisor_num += 2

    if int(sqrt_v) == sqrt_v:
        if triangle_v % sqrt_v == 0:
            divisor_num += 1
    else:
        if triangle_v % int(sqrt_v) == 0:
            divisor_num += 2

    if divisor_num > 500:
        print triangle_v
        break

